window.__LOCALE_MAP = [
  ['Complete sign-in in the new tab, then close it to continue.', '在新标签页中完成登录后关闭此页以继续。'],
  ['Waiting for OIDC sign-in...', '等待 OIDC 登录……'],
  ["You've reached the end", '已无更多内容'],
  ['Expires after inactivity (seconds, 0 = never)', '无操作过期时间（秒，0 = 永不过期）'],
  ['Password (empty if no change)', '密码（不修改请留空）'],
  ['Elevation failed. Check your password.', '提升权限失败，请检查密码。'],
  ['This action requires re-authentication.', '此操作需要重新验证身份。'],
  ['Elevate with Password', '使用密码提升权限'],
  ['Cancel OIDC Login', '取消 OIDC 登录'],
  ['Confirm Token Regeneration', '确认重新生成令牌'],
  ['Elevate via OIDC', '通过 OIDC 提升权限'],
  ['has administrator rights', '拥有管理员权限'],
  ['Confirm Delete Image', '确认删除图片'],
  ['Enable Notifications', '启用通知'],
  ['Token Confirmation', '令牌确认'],
  ['Copy to clipboard', '复制到剪贴板'],
  ['Change Password', '修改密码'],
  ['Cannot access clipboard.', '无法访问剪贴板。'],
  ['Authenticaton Required', '需要身份验证'],
  ['Delete all messages?', '删除所有消息？'],
  ['Create Application', '创建应用'],
  ['New Password *', '新密码 *'],
  ['Password is required', '请输入密码'],
  ['username is required', '请输入用户名'],
  ['password is required', '请输入密码'],
  ['name is required', '请输入名称'],
  ['Create a client', '创建客户端'],
  ['Delete All', '删除全部'],
  ['Push Message', '推送消息'],
  ['Confirm Delete', '确认删除'],
  ['All Messages', '所有消息'],
  ['No messages', '暂无消息'],
  ['Some Server', '示例服务器'],
  ['A Raspberry PI', '树莓派'],
  ['Message deleted', '消息已删除'],
  ['Copied to clipboard', '已复制到剪贴板'],
  ['Toggle theme (current: dark)', '切换主题（当前：深色）'],
  ['Toggle theme (current: light)', '切换主题（当前：浅色）'],
  ['Toggle theme (current: system)', '切换主题（当前：系统）'],
  ['Login with OIDC', '通过 OIDC 登录'],
  ['Delete image', '删除图片'],
  ['Add a user', '添加用户'],
  ['Applications', '应用'],
  ['Description', '描述'],
  ['Priority', '优先级'],
  ['Last Used', '上次使用'],
  ['Create User', '创建用户'],
  ['Create Client', '创建客户端'],
  ['Elevation ends', '权限提升结束'],
  ['Expires in', '剩余时间'],
  ['Settings', '设置'],
  ['Username *', '用户名 *'],
  ['Password *', '密码 *'],
  ['Logout', '退出登录'],
  ['Register', '注册'],
  ['Username', '用户名'],
  ['Password', '密码'],
  ['Plugins', '插件'],
  ['plugins', '插件'],
  ['Clients', '客户端'],
  ['clients', '客户端'],
  ['Created', '创建时间'],
  ['Details', '详情'],
  ['Refresh', '刷新'],
  ['Enabled', '已启用'],
  ['Elevate', '提升权限'],
  ['Cancel', '取消'],
  ['Finish', '完成'],
  ['Users', '用户'],
  ['users', '用户'],
  ['apps', '应用'],
  ['menu', '菜单'],
  ['Admin', '管理员'],
  ['Token', '令牌'],
  ['Name', '名称'],
  ['Name *', '名称 *'],
  ['Save', '保存'],
  ['Create', '创建'],
  ['Change', '修改'],
  ['Retry', '重试'],
  ['Undo', '撤销'],
  ['Login', '登录'],
  ['Yes', '是'],
  ['No', '否'],
  ['or', '或'],
  ['ID', '编号'],
  ['Copied', '已复制'],
  ['Messages', '消息'],
  ['Search', '搜索'],
  ['Delete', '删除'],
  ['Edit', '编辑'],
  ['Update', '更新'],
  ['Show', '显示'],
  ['Hide', '隐藏'],
  ['Global', '全局'],
  ['High', '高'],
  ['Normal', '普通'],
  ['Low', '低'],
  ['Application created', '应用已创建'],
  ['Application deleted', '应用已删除'],
  ['Application updated', '应用已更新'],
  ['Client created', '客户端已创建'],
  ['Client deleted', '客户端已删除'],
  ['User created', '用户已创建'],
  ['User deleted', '用户已删除'],
  ['Old Password', '旧密码'],
  ['Passwords do not match', '密码不匹配'],
  ['All Plugins', '所有插件'],
  ['About', '关于'],
  ['Version', '版本'],
  ['Profile', '个人信息'],
  ['Themes', '主题'],
  ['Dark', '深色'],
  ['Light', '浅色'],
  ['System', '系统默认'],
  ['Back to reference', '返回参考页'],
  ['WebSocket connection closed, trying again in 30 seconds.', 'WebSocket 连接已关闭，30 秒后重试。'],
  ['No network connection or server unavailable.', '无网络连接或服务器不可用。'],
  ['Login failed', '登录失败'],
  ['Reconnect failed', '重新连接失败'],
  ['Failed to copy to clipboard', '复制到剪贴板失败'],
  ['Password changed', '密码已修改'],
  ['Client added', '客户端已添加'],
  ['Client updated', '客户端已更新'],
  ['User updated', '用户已更新'],
  ['User Created. Logging in...', '用户已创建，正在登录……'],
  ['Could not authenticate with client token, logging out.', '无法使用客户端令牌验证身份，正在退出登录。'],
  ['Application image deleted', '应用图片已删除'],
  ['Application image updated', '应用图片已更新'],
  ['Cannot delete plugin', '无法删除插件'],
  ['Plugin config updated', '插件配置已更新'],
  ['Deleted all messages', '已删除所有消息'],
  ['Short Description', '简要描述'],
  ['Default Priority', '默认优先级'],
  ['Title', '标题'],
  ['Message sent to', '消息已发送至'],
  ['Register failed', '注册失败'],
  ['Plugin enabled', '插件已启用'],
  ['Plugin disabled', '插件已禁用'],
  ['was created for your session.', '。'],
  ['A client named', '已为当前会话创建客户端'],
  ['Deleted all messages from ', '已删除来自 '],
  ['Popup was blocked. Please allow popups for this site and try again.', '弹出窗口被阻止，请允许此站点显示弹出窗口后重试。'],
  ['OIDC elevation was not completed.', 'OIDC 权限提升未完成。'],
  ['Gotify server is not reachable, try refreshing the page.', 'Gotify 服务器无法访问，请尝试刷新页面。'],
  ['Could not complete request.', '请求失败。'],
];
