window.__LOCALE_MAP = [
  ['Complete sign-in in the new tab, then close it to continue.', '在新标签页中完成登录后关闭此页以继续。'],
  ['Waiting for OIDC sign-in...', '等待 OIDC 登录……'],
  ["You've reached the end", '已到末尾'],
  ['Expires after inactivity (seconds, 0 = never)', '无操作后过期（秒，0 = 永不过期）'],
  ['Password (empty if no change)', '密码（不修改留空）'],
  ['Elevation failed. Check your password.', '提升权限失败，请检查密码。'],
  ['This action requires re-authentication.', '此操作需要重新验证身份。'],
  ['Elevate with Password', '使用密码提升权限'],
  ['Cancel OIDC Login', '取消 OIDC 登录'],
  ['Confirm Token Regeneration', '确认重新生成令牌'],
  ['Elevate via OIDC', '通过 OIDC 提升权限'],
  ['has administrator rights', '拥有管理员权限'],
  ['Confirm Delete Image', '确认删除图片'],
  ['Enable Notifications', '启用通知'],
  ['Token Confirmation', '令牌确认'],
  ['Copy to clipboard', '复制到剪贴板'],
  ['Change Password', '修改密码'],
  ['Cannot access clipboard.', '无法访问剪贴板。'],
  ['Authenticaton Required', '需要验证'],
  ['Delete all messages?', '删除所有消息？'],
  ['Create Application', '创建应用'],
  ['New Password *', '新密码 *'],
  ['Password is required', '请输入密码'],
  ['username is required', '请输入用户名'],
  ['password is required', '请输入密码'],
  ['name is required', '请输入名称'],
  ['Create a client', '创建客户端'],
  ['Delete All', '删除全部'],
  ['Push Message', '推送消息'],
  ['Confirm Delete', '确认删除'],
  ['All Messages', '所有消息'],
  ['No messages', '暂无消息'],
  ['Some Server', '某服务器'],
  ['A Raspberry PI', '树莓派'],
  ['Message deleted', '消息已删除'],
  ['Copied to clipboard', '已复制到剪贴板'],
  ['Toggle theme (current: dark)', '切换主题（当前：深色）'],
  ['Toggle theme (current: light)', '切换主题（当前：浅色）'],
  ['Toggle theme (current: system)', '切换主题（当前：系统）'],
  ['Login with OIDC', '通过 OIDC 登录'],
  ['Delete image', '删除图片'],
  ['Add a user', '添加用户'],
  ['Applications', '应用'],
  ['Description', '描述'],
  ['Priority', '优先级'],
  ['Last Used', '上次使用'],
  ['Create User', '创建用户'],
  ['Create Client', '创建客户端'],
  ['Elevation ends', '权限提升到期'],
  ['Expires in', '过期时间'],
  ['Settings', '设置'],
  ['Username *', '用户名 *'],
  ['Password *', '密码 *'],
  ['Logout', '退出登录'],
  ['Register', '注册'],
  ['Username', '用户名'],
  ['Password', '密码'],
  ['Plugins', '插件'],
  ['Clients', '客户端'],
  ['Created', '创建时间'],
  ['Details', '详情'],
  ['Refresh', '刷新'],
  ['Enabled', '已启用'],
  ['Elevate', '提升权限'],
  ['Cancel', '取消'],
  ['Finish', '完成'],
  ['Users', '用户管理'],
  ['apps', '应用'],
  ['menu', '菜单'],
  ['Admin', '管理员'],
  ['Token', '令牌'],
  ['Name', '名称'],
  ['Name *', '名称 *'],
  ['Save', '保存'],
  ['Create', '创建'],
  ['Change', '修改'],
  ['Retry', '重试'],
  ['Undo', '撤销'],
  ['Login', '登录'],
  ['Yes', '是'],
  ['No', '否'],
  ['or', '或'],
  ['ID', '编号'],
  ['Copied', '已复制'],
];
