services:
  gotify:
    image: gotify/server:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - gotify-data:/app/data

  gotify-gw:
    image: zerocustom/gotify-e:latest
    restart: unless-stopped
    ports:
      - 8765:8765
    environment:
      - GOTIFY_BACKEND=http://gotify:80
      - PUBLIC_URL=http://localhost:8765
      - HOST=0.0.0.0
      - PORT=8765
      - STORED_MARKER={gateway}
    volumes:
      - uploads-data:/data
    depends_on:
      - gotify
